/* This list all the variables for a postgresql request in the database 
   not used for the application */
export const VARIABLE_LIST: string[] = [
    '% Edi Cycle Off In NAVA',
    '% Edi Trigger In NAVA',
    'Access pressure mmHg',
    'Anticoagulant bolus interval hr',
    'Anticoagulant bolus volume ml',
    'Anticoagulant continuous rate ml/hr',
    'AoD',
    'AoM',
    'AoS',
    'Apnea Time Interval Setting',
    'ARTd',
    'ARTm',
    'ARTs',
    'Backup Pressure Level Above PEEP',
    'BL-1',
    'BL-2',
    'Blood flow rate ml/min',
    'CMV frequency Setting',
    'CO2fe','CO2mi',
    'Cycle Off Fraction Level Setting',
    'DCC',
    'Device Name',
    'Dialysate flow rate ml/hr',
    'Dialysate volume',
    'dPmax',
    'Ectopq',
    'Edi Trigger Setting',
    'Effluent flow rate ml/hr',
    'Effluent pressure mmHg',
    'Effluent volume','ESV',
    'Excess patient fluid limit ml',
    'Excess patient fluid ml',
    'Expiratory Minute Volume',
    'Expiratory Minute Volume Lower Alarm Limit',
    'Expiratory Minute Volume Upper Alarm Limit',
    'Expiratory Tidal Volume',
    'FC',
    'Filter pressure mmHg',
    'FR',
    'FR-aer',
    'ICC',
    'IE Ratio',
    'IE Ratio Setting',
    'Inspiratory Flow Setting',
    'Inspiratory Rise time Setting sec',
    'Inspiratory Time Setting',
    'IPI',
    'ISO-fe',
    'IVEj',
    'MAC',
    'Machine number',
    'Maximum volum gain ml',
    'Mean Airway Pressure',
    'Measured Frequency',
    'Minimum Diaphragm Electrical Activity (Edi)',
    'N2O-fe','N2O-in','NAVA Level Setting',
    'Next intervention time Hour',
    'Next intervention time Minute',
    'NIV Leakage Fraction',
    'O2 Concentration measured',
    'O2 Concentration Setting',
    'O2-fe',
    'O2-in',
    'P1m',
    'P2d',
    'P2m',
    'P2s',
    'P4d',
    'P4m',
    'P4s',
    'PAd',
    'PAm',
    'PAOd',
    'PAOm',
    'PAOs',
    'PAPd',
    'PAPm',
    'PAPs',
    'PAs',
    'PCTBL1',
    'PCTBL2',
    'Pd',
    'Peak Airway Pressure',
    'Peak Diaphragm Electrical Activity (Edi)',
    'Peak Pressure Upper Alarm Limit',
    'PEEP Setting',
    'Perf',
    'Perf g',
    'PerfPr',
    'PICm',
    'Pm',
    'PODm',
    'POGd',
    'POGm',
    'POGs',
    'Positive End Expiratory Pressure (PEEP)',
    'Pouls (ART)',
    'Pouls (P)',
    'Pouls (PA)',
    'Pouls (SpO2)',
    'Pouls(SpO2g)',
    'PPC',
    'Pre Blood volume ml',
    'Pre-blood flow rate ml/hr',
    'Pressure Control Level Above PEEP',
    'Pressure drop mmHg',
    'Pressure Support Level Above PEEP',
    'Processed blood volume litre',
    'Ps','Pt weight balance ml/hr',
    'Pt weight cumulated kg',
    'Pt weight kg',
    'PVCd',
    'PVCm',
    'PVCs',
    'PVOm',
    'QT',
    'QT-FC',
    'QTc',
    'Replacement POST volume ml',
    'Replacement post-flow rate ml/hr',
    'Replacement PRE volume ml',
    'Replacement pre-flow rate ml/hr',
    'Return pressure mmHg',
    'rSO2-1',
    'rSO2-2',
    'rSO2-3',
    'rSO2-4',
    'RVS',
    'Rythme',
    'SIMV Frequency Setting',
    'SpO2',
    'SpO2g',
    'SpO2pr',
    'Spontaneous Frequency measured',
    'ST-II',
    'ST-III',
    'T1',
    'Temp',
    'Therapy run time sec',
    'Therapy type (numeric)',
    'Tidal Volume Setting',
    'Tnaso',
    'Toeso',
    'Transmembrane pressure mmHg',
    'Trect',
    'Trigger Sensitivity Above PEEP',
    'Trigger Sensitivity Below PEEP',
    'TSang','TYPE',
    'Ultrafiltration ration %',
    'VEj',
    'Ventilation Mode Setting',
    'VVS'
]